#cloud-config
debug: true
hostname: nas-{{ trunc 4 .MachineID }}
# fail on cloud config errors
strict: true
install:
    ephemeral_mounts:
        - /scratch
    bind_mounts:
        - /var/lib/docker
    extra-dirs-rootfs:
        - /data
        - /services
        - /scratch
    poweroff: true
    reboot: false
reset:
    poweroff: true
    reboot: true
    reset-persistent: false
    reset-oem: false
    ephemeral_mounts:
        - /scratch
    bind_mounts:
        - /var/lib/docker
    extra-dirs-rootfs:
        - /data
        - /services
        - /scratch
upgrade:
    poweroff: true
    reboot: true
    bind_mounts:
        - /var/lib/docker
    ephemeral_mounts:
        - /scratch
    extra-dirs-rootfs:
        - /data
        - /services
        - /scratch
ssh_pwauth: false
timezone: America/Los_Angeles
stages:
    initramfs:
      - name: "create base users"
        users:
         - name: clayton
           groups:
             - admin
             - docker
           lock_passwd: true
           shell: /usr/bin/fish
           ssh_authorized_keys:
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOTdQLlqHFSdRU4iYNTx4Dgl+BUKnmSeV1od4BCvot0 clayton@ClaytonsMacBookPro.socal.rr.com
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/1VzaIV0bnoIv//1FtbRSnwv5KE7KP/sgljykiqTLa mini
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOz0v4rsoL7f/A118ry+wWPd68pcvhkxrd0ITi8feUKQ mb-air
         - name: test
           groups:
             - admin
             - docker
           lock_passwd: true
           shell: /usr/bin/fish
           ssh_authorized_keys:
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOTdQLlqHFSdRU4iYNTx4Dgl+BUKnmSeV1od4BCvot0 clayton@ClaytonsMacBookPro.socal.rr.com
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/1VzaIV0bnoIv//1FtbRSnwv5KE7KP/sgljykiqTLa mini
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOz0v4rsoL7f/A118ry+wWPd68pcvhkxrd0ITi8feUKQ mb-air
         - name: git
           lock_passwd: true
           shell: /usr/bin/git-shell
           ssh_authorized_keys:
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOTdQLlqHFSdRU4iYNTx4Dgl+BUKnmSeV1od4BCvot0 clayton@ClaytonsMacBookPro.socal.rr.com
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/1VzaIV0bnoIv//1FtbRSnwv5KE7KP/sgljykiqTLa mini
             - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOz0v4rsoL7f/A118ry+wWPd68pcvhkxrd0ITi8feUKQ mb-air
    fs:
      - name: Import ZPool
        commands:
          - zpool import -af
      - name: mount data drive
        commands:
          - mount /dev/disk/by-id/ata-ST12000NM001G-2MV103_ZLW20B65 /data
      - name: clone dotfiles
        git:
          branch: main
          path: /scratch/dotfiles
          url: https://github.com/clanktron/dotfiles
      - name: install dotfiles
        commands:
          - chown -R test:test /scratch/dotfiles && cd /scratch/dotfiles && su test -c "HOME=/home/test XDG_CONFIG_HOME=/home/test/.config ./install link"
