#cloud-config

# https://github.com/kairos-io/kairos/issues/1963
debug: true
hostname: nas
stages:
  initramfs:
    - name: ensure users
      users:
        clayton: 
          shell: /usr/bin/fish
          passwd: clayton
          groups:
            - admin
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOTdQLlqHFSdRU4iYNTx4Dgl+BUKnmSeV1od4BCvot0 clayton@ClaytonsMacBookPro.socal.rr.com
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/1VzaIV0bnoIv//1FtbRSnwv5KE7KP/sgljykiqTLa mini
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOz0v4rsoL7f/A118ry+wWPd68pcvhkxrd0ITi8feUKQ mb-air
        git:
          shell: /usr/bin/git-shell
          passwd: git
  fs:
    - name: install dotfiles
      git:
        branch: main
        path: /scratch/dotfiles
        url: https://github.com/clanktron/dotfiles
      commands:
        - chown -R clayton:clayton /scratch/dotfiles && su clayton -c "HOME=/home/clayton /scratch/dotfiles/install -l"
install:
  image: quay.io/clanktron/nas:0.1.2
  ephemeral_mounts:
    - /scratch
  bind_mounts:
    - /var/lib/tailscale
  extra-dirs-rootfs:
    - /data
    - /services
    - /scratch
    - /s3
  poweroff: true
  reboot: false
