#cloud-config

# https://github.com/kairos-io/kairos/issues/1963
debug: true
hostname: nas
stages:
  initramfs:
    - name: ensure users
      users:
        clayton: 
          passwd: clayton
          groups:
            - admin
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOTdQLlqHFSdRU4iYNTx4Dgl+BUKnmSeV1od4BCvot0 clayton@ClaytonsMacBookPro.socal.rr.com
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/1VzaIV0bnoIv//1FtbRSnwv5KE7KP/sgljykiqTLa mini
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOz0v4rsoL7f/A118ry+wWPd68pcvhkxrd0ITi8feUKQ mb-air
        git:
          passwd: git
install:
  image: quay.io/clanktron/nas-ubuntu:latest
  ephemeral_mounts:
    - /scratch
  bind_mounts:
    - /var/lib/tailscale
  extra-dirs-rootfs:
    - /data
    - /services
    - /scratch
    - /s3
  poweroff: true
  reboot: false
