#cloud-config
debug: true
hostname: nas
# fail on cloud config errors
strict: false
users:
  - name: test
    userid: 4004
    groups:
      - admin
      - docker
    passwd: mudlermudlermudler
    shell: /usr/bin/fish
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOTdQLlqHFSdRU4iYNTx4Dgl+BUKnmSeV1od4BCvot0 clayton@ClaytonsMacBookPro.socal.rr.com
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/1VzaIV0bnoIv//1FtbRSnwv5KE7KP/sgljykiqTLa mini
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOz0v4rsoL7f/A118ry+wWPd68pcvhkxrd0ITi8feUKQ mb-air
install:
  image: quay.io/clanktron/nas-tumbleweed:5ce583d4a41a1a92d0f4b807d233e6ba7785c45c
  ephemeral_mounts:
    - /scratch
  bind_mounts:
    - /var/lib/docker
    - /var/lib/tailscale
  extra-dirs-rootfs:
    - /data
    - /services
    - /scratch
    - /s3
  poweroff: true
  reboot: false
ssh_pwauth: false
timezone: America/Los_Angeles
stages:
  initramfs:
    - name: ensure user
      users:
        - name: clayton
          userid: 4000
          groups:
            - admin
            - docker
          lock_passwd: true
          shell: /usr/bin/fish
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDOTdQLlqHFSdRU4iYNTx4Dgl+BUKnmSeV1od4BCvot0 clayton@ClaytonsMacBookPro.socal.rr.com
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/1VzaIV0bnoIv//1FtbRSnwv5KE7KP/sgljykiqTLa mini
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOz0v4rsoL7f/A118ry+wWPd68pcvhkxrd0ITi8feUKQ mb-air
  boot:
    - name: really ensure user
      ensure_entities:
       -  path: /etc/passwd
          entity: |
                  kind: "user"
                  username: "foobar"
                  password: "barfoo"
                  uid: 4040
                  gid: 4040
                  homedir: "/home/foo"
                  shell: "/usr/bin/fish"
